/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GestolenRouteImport } from './routes/gestolen'
import { Route as FietsControlerenRouteImport } from './routes/fiets-controleren'
import { Route as DedupAuditRouteImport } from './routes/dedup-audit'
import { Route as BikesearchRouteImport } from './routes/bikesearch'
import { Route as BestellenRouteImport } from './routes/bestellen'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlEenStickerRouteImport } from './routes/al-een-sticker'
import { Route as AdminAuthCheckRouteImport } from './routes/admin-auth-check'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as MTokenRouteImport } from './routes/m.$token'
import { Route as BestellenBedanktRouteImport } from './routes/bestellen.bedankt'
import { Route as AdminAdminWebhooksRouteImport } from './routes/_admin/admin-webhooks'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin-users'
import { Route as AdminAdminShopSignupsRouteImport } from './routes/_admin/admin-shop-signups'
import { Route as AdminAdminMarginPollRouteImport } from './routes/_admin/admin-margin-poll'
import { Route as AdminAdminEmailLogRouteImport } from './routes/_admin/admin-email-log'
import { Route as AdminAdminEmailEventsRouteImport } from './routes/_admin/admin-email-events'
import { Route as AdminAdminAuditRouteImport } from './routes/_admin/admin-audit'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LangStolenRouteImport } from './routes/$lang/stolen'
import { Route as LangShopRouteImport } from './routes/$lang/shop'
import { Route as LangProRouteImport } from './routes/$lang/pro'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangOrderRouteImport } from './routes/$lang/order'
import { Route as LangManufacturerRouteImport } from './routes/$lang/manufacturer'
import { Route as LangLeasingRouteImport } from './routes/$lang/leasing'
import { Route as LangInsuranceRouteImport } from './routes/$lang/insurance'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangBikeCheckRouteImport } from './routes/$lang/bike-check'
import { Route as LangAssistanceRouteImport } from './routes/$lang/assistance'
import { Route as LangAlreadyHaveOneRouteImport } from './routes/$lang/already-have-one'
import { Route as ApiPublicViesLookupRouteImport } from './routes/api/public/vies-lookup'
import { Route as ApiPublicShopSignupRouteImport } from './routes/api/public/shop-signup'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LangOrderThanksRouteImport } from './routes/$lang/order_.thanks'
import { Route as LangGuidesBuyingSecondHandRouteImport } from './routes/$lang/guides.buying-second-hand'
import { Route as ApiPublicPaymentsMollieWebhookRouteImport } from './routes/api/public/payments/mollie-webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GestolenRoute = GestolenRouteImport.update({
  id: '/gestolen',
  path: '/gestolen',
  getParentRoute: () => rootRouteImport,
} as any)
const FietsControlerenRoute = FietsControlerenRouteImport.update({
  id: '/fiets-controleren',
  path: '/fiets-controleren',
  getParentRoute: () => rootRouteImport,
} as any)
const DedupAuditRoute = DedupAuditRouteImport.update({
  id: '/dedup-audit',
  path: '/dedup-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesearchRoute = BikesearchRouteImport.update({
  id: '/bikesearch',
  path: '/bikesearch',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellenRoute = BestellenRouteImport.update({
  id: '/bestellen',
  path: '/bestellen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlEenStickerRoute = AlEenStickerRouteImport.update({
  id: '/al-een-sticker',
  path: '/al-een-sticker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthCheckRoute = AdminAuthCheckRouteImport.update({
  id: '/admin-auth-check',
  path: '/admin-auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const MTokenRoute = MTokenRouteImport.update({
  id: '/m/$token',
  path: '/m/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellenBedanktRoute = BestellenBedanktRouteImport.update({
  id: '/bedankt',
  path: '/bedankt',
  getParentRoute: () => BestellenRoute,
} as any)
const AdminAdminWebhooksRoute = AdminAdminWebhooksRouteImport.update({
  id: '/admin-webhooks',
  path: '/admin-webhooks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminShopSignupsRoute = AdminAdminShopSignupsRouteImport.update({
  id: '/admin-shop-signups',
  path: '/admin-shop-signups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminMarginPollRoute = AdminAdminMarginPollRouteImport.update({
  id: '/admin-margin-poll',
  path: '/admin-margin-poll',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminEmailLogRoute = AdminAdminEmailLogRouteImport.update({
  id: '/admin-email-log',
  path: '/admin-email-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminEmailEventsRoute = AdminAdminEmailEventsRouteImport.update({
  id: '/admin-email-events',
  path: '/admin-email-events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: '/admin-audit',
  path: '/admin-audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangStolenRoute = LangStolenRouteImport.update({
  id: '/stolen',
  path: '/stolen',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangShopRoute = LangShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangProRoute = LangProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangOrderRoute = LangOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangManufacturerRoute = LangManufacturerRouteImport.update({
  id: '/manufacturer',
  path: '/manufacturer',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLeasingRoute = LangLeasingRouteImport.update({
  id: '/leasing',
  path: '/leasing',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangInsuranceRoute = LangInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBikeCheckRoute = LangBikeCheckRouteImport.update({
  id: '/bike-check',
  path: '/bike-check',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAssistanceRoute = LangAssistanceRouteImport.update({
  id: '/assistance',
  path: '/assistance',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAlreadyHaveOneRoute = LangAlreadyHaveOneRouteImport.update({
  id: '/already-have-one',
  path: '/already-have-one',
  getParentRoute: () => LangRouteRoute,
} as any)
const ApiPublicViesLookupRoute = ApiPublicViesLookupRouteImport.update({
  id: '/api/public/vies-lookup',
  path: '/api/public/vies-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopSignupRoute = ApiPublicShopSignupRouteImport.update({
  id: '/api/public/shop-signup',
  path: '/api/public/shop-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangOrderThanksRoute = LangOrderThanksRouteImport.update({
  id: '/order_/thanks',
  path: '/order/thanks',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangGuidesBuyingSecondHandRoute =
  LangGuidesBuyingSecondHandRouteImport.update({
    id: '/guides/buying-second-hand',
    path: '/guides/buying-second-hand',
    getParentRoute: () => LangRouteRoute,
  } as any)
const ApiPublicPaymentsMollieWebhookRoute =
  ApiPublicPaymentsMollieWebhookRouteImport.update({
    id: '/api/public/payments/mollie-webhook',
    path: '/api/public/payments/mollie-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/admin-auth-check': typeof AdminAuthCheckRoute
  '/al-een-sticker': typeof AlEenStickerRoute
  '/auth': typeof AuthRoute
  '/bestellen': typeof BestellenRouteWithChildren
  '/bikesearch': typeof BikesearchRoute
  '/dedup-audit': typeof DedupAuditRoute
  '/fiets-controleren': typeof FietsControlerenRoute
  '/gestolen': typeof GestolenRoute
  '/mcp': typeof McpRoute
  '/professionals': typeof ProfessionalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/already-have-one': typeof LangAlreadyHaveOneRoute
  '/$lang/assistance': typeof LangAssistanceRoute
  '/$lang/bike-check': typeof LangBikeCheckRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/insurance': typeof LangInsuranceRoute
  '/$lang/leasing': typeof LangLeasingRoute
  '/$lang/manufacturer': typeof LangManufacturerRoute
  '/$lang/order': typeof LangOrderRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/pro': typeof LangProRoute
  '/$lang/shop': typeof LangShopRoute
  '/$lang/stolen': typeof LangStolenRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AdminAdminRoute
  '/admin-audit': typeof AdminAdminAuditRoute
  '/admin-email-events': typeof AdminAdminEmailEventsRoute
  '/admin-email-log': typeof AdminAdminEmailLogRoute
  '/admin-margin-poll': typeof AdminAdminMarginPollRoute
  '/admin-shop-signups': typeof AdminAdminShopSignupsRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/admin-webhooks': typeof AdminAdminWebhooksRoute
  '/bestellen/bedankt': typeof BestellenBedanktRoute
  '/m/$token': typeof MTokenRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/guides/buying-second-hand': typeof LangGuidesBuyingSecondHandRoute
  '/$lang/order/thanks': typeof LangOrderThanksRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/shop-signup': typeof ApiPublicShopSignupRoute
  '/api/public/vies-lookup': typeof ApiPublicViesLookupRoute
  '/api/public/payments/mollie-webhook': typeof ApiPublicPaymentsMollieWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-auth-check': typeof AdminAuthCheckRoute
  '/al-een-sticker': typeof AlEenStickerRoute
  '/auth': typeof AuthRoute
  '/bestellen': typeof BestellenRouteWithChildren
  '/bikesearch': typeof BikesearchRoute
  '/dedup-audit': typeof DedupAuditRoute
  '/fiets-controleren': typeof FietsControlerenRoute
  '/gestolen': typeof GestolenRoute
  '/mcp': typeof McpRoute
  '/professionals': typeof ProfessionalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/already-have-one': typeof LangAlreadyHaveOneRoute
  '/$lang/assistance': typeof LangAssistanceRoute
  '/$lang/bike-check': typeof LangBikeCheckRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/insurance': typeof LangInsuranceRoute
  '/$lang/leasing': typeof LangLeasingRoute
  '/$lang/manufacturer': typeof LangManufacturerRoute
  '/$lang/order': typeof LangOrderRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/pro': typeof LangProRoute
  '/$lang/shop': typeof LangShopRoute
  '/$lang/stolen': typeof LangStolenRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AdminAdminRoute
  '/admin-audit': typeof AdminAdminAuditRoute
  '/admin-email-events': typeof AdminAdminEmailEventsRoute
  '/admin-email-log': typeof AdminAdminEmailLogRoute
  '/admin-margin-poll': typeof AdminAdminMarginPollRoute
  '/admin-shop-signups': typeof AdminAdminShopSignupsRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/admin-webhooks': typeof AdminAdminWebhooksRoute
  '/bestellen/bedankt': typeof BestellenBedanktRoute
  '/m/$token': typeof MTokenRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/guides/buying-second-hand': typeof LangGuidesBuyingSecondHandRoute
  '/$lang/order/thanks': typeof LangOrderThanksRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/shop-signup': typeof ApiPublicShopSignupRoute
  '/api/public/vies-lookup': typeof ApiPublicViesLookupRoute
  '/api/public/payments/mollie-webhook': typeof ApiPublicPaymentsMollieWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/_admin': typeof AdminRouteRouteWithChildren
  '/admin-auth-check': typeof AdminAuthCheckRoute
  '/al-een-sticker': typeof AlEenStickerRoute
  '/auth': typeof AuthRoute
  '/bestellen': typeof BestellenRouteWithChildren
  '/bikesearch': typeof BikesearchRoute
  '/dedup-audit': typeof DedupAuditRoute
  '/fiets-controleren': typeof FietsControlerenRoute
  '/gestolen': typeof GestolenRoute
  '/mcp': typeof McpRoute
  '/professionals': typeof ProfessionalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/already-have-one': typeof LangAlreadyHaveOneRoute
  '/$lang/assistance': typeof LangAssistanceRoute
  '/$lang/bike-check': typeof LangBikeCheckRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/insurance': typeof LangInsuranceRoute
  '/$lang/leasing': typeof LangLeasingRoute
  '/$lang/manufacturer': typeof LangManufacturerRoute
  '/$lang/order': typeof LangOrderRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/pro': typeof LangProRoute
  '/$lang/shop': typeof LangShopRoute
  '/$lang/stolen': typeof LangStolenRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/_admin/admin-audit': typeof AdminAdminAuditRoute
  '/_admin/admin-email-events': typeof AdminAdminEmailEventsRoute
  '/_admin/admin-email-log': typeof AdminAdminEmailLogRoute
  '/_admin/admin-margin-poll': typeof AdminAdminMarginPollRoute
  '/_admin/admin-shop-signups': typeof AdminAdminShopSignupsRoute
  '/_admin/admin-users': typeof AdminAdminUsersRoute
  '/_admin/admin-webhooks': typeof AdminAdminWebhooksRoute
  '/bestellen/bedankt': typeof BestellenBedanktRoute
  '/m/$token': typeof MTokenRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/guides/buying-second-hand': typeof LangGuidesBuyingSecondHandRoute
  '/$lang/order_/thanks': typeof LangOrderThanksRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/shop-signup': typeof ApiPublicShopSignupRoute
  '/api/public/vies-lookup': typeof ApiPublicViesLookupRoute
  '/api/public/payments/mollie-webhook': typeof ApiPublicPaymentsMollieWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin-auth-check'
    | '/al-een-sticker'
    | '/auth'
    | '/bestellen'
    | '/bikesearch'
    | '/dedup-audit'
    | '/fiets-controleren'
    | '/gestolen'
    | '/mcp'
    | '/professionals'
    | '/reset-password'
    | '/sitemap.xml'
    | '/$lang/already-have-one'
    | '/$lang/assistance'
    | '/$lang/bike-check'
    | '/$lang/contact'
    | '/$lang/insurance'
    | '/$lang/leasing'
    | '/$lang/manufacturer'
    | '/$lang/order'
    | '/$lang/privacy'
    | '/$lang/pro'
    | '/$lang/shop'
    | '/$lang/stolen'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/admin-audit'
    | '/admin-email-events'
    | '/admin-email-log'
    | '/admin-margin-poll'
    | '/admin-shop-signups'
    | '/admin-users'
    | '/admin-webhooks'
    | '/bestellen/bedankt'
    | '/m/$token'
    | '/$lang/'
    | '/$lang/guides/buying-second-hand'
    | '/$lang/order/thanks'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/shop-signup'
    | '/api/public/vies-lookup'
    | '/api/public/payments/mollie-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-auth-check'
    | '/al-een-sticker'
    | '/auth'
    | '/bestellen'
    | '/bikesearch'
    | '/dedup-audit'
    | '/fiets-controleren'
    | '/gestolen'
    | '/mcp'
    | '/professionals'
    | '/reset-password'
    | '/sitemap.xml'
    | '/$lang/already-have-one'
    | '/$lang/assistance'
    | '/$lang/bike-check'
    | '/$lang/contact'
    | '/$lang/insurance'
    | '/$lang/leasing'
    | '/$lang/manufacturer'
    | '/$lang/order'
    | '/$lang/privacy'
    | '/$lang/pro'
    | '/$lang/shop'
    | '/$lang/stolen'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/admin-audit'
    | '/admin-email-events'
    | '/admin-email-log'
    | '/admin-margin-poll'
    | '/admin-shop-signups'
    | '/admin-users'
    | '/admin-webhooks'
    | '/bestellen/bedankt'
    | '/m/$token'
    | '/$lang'
    | '/$lang/guides/buying-second-hand'
    | '/$lang/order/thanks'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/shop-signup'
    | '/api/public/vies-lookup'
    | '/api/public/payments/mollie-webhook'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/_admin'
    | '/admin-auth-check'
    | '/al-een-sticker'
    | '/auth'
    | '/bestellen'
    | '/bikesearch'
    | '/dedup-audit'
    | '/fiets-controleren'
    | '/gestolen'
    | '/mcp'
    | '/professionals'
    | '/reset-password'
    | '/sitemap.xml'
    | '/$lang/already-have-one'
    | '/$lang/assistance'
    | '/$lang/bike-check'
    | '/$lang/contact'
    | '/$lang/insurance'
    | '/$lang/leasing'
    | '/$lang/manufacturer'
    | '/$lang/order'
    | '/$lang/privacy'
    | '/$lang/pro'
    | '/$lang/shop'
    | '/$lang/stolen'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_admin/admin'
    | '/_admin/admin-audit'
    | '/_admin/admin-email-events'
    | '/_admin/admin-email-log'
    | '/_admin/admin-margin-poll'
    | '/_admin/admin-shop-signups'
    | '/_admin/admin-users'
    | '/_admin/admin-webhooks'
    | '/bestellen/bedankt'
    | '/m/$token'
    | '/$lang/'
    | '/$lang/guides/buying-second-hand'
    | '/$lang/order_/thanks'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/shop-signup'
    | '/api/public/vies-lookup'
    | '/api/public/payments/mollie-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AdminAuthCheckRoute: typeof AdminAuthCheckRoute
  AlEenStickerRoute: typeof AlEenStickerRoute
  AuthRoute: typeof AuthRoute
  BestellenRoute: typeof BestellenRouteWithChildren
  BikesearchRoute: typeof BikesearchRoute
  DedupAuditRoute: typeof DedupAuditRoute
  FietsControlerenRoute: typeof FietsControlerenRoute
  GestolenRoute: typeof GestolenRoute
  McpRoute: typeof McpRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  MTokenRoute: typeof MTokenRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicShopSignupRoute: typeof ApiPublicShopSignupRoute
  ApiPublicViesLookupRoute: typeof ApiPublicViesLookupRoute
  ApiPublicPaymentsMollieWebhookRoute: typeof ApiPublicPaymentsMollieWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestolen': {
      id: '/gestolen'
      path: '/gestolen'
      fullPath: '/gestolen'
      preLoaderRoute: typeof GestolenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiets-controleren': {
      id: '/fiets-controleren'
      path: '/fiets-controleren'
      fullPath: '/fiets-controleren'
      preLoaderRoute: typeof FietsControlerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dedup-audit': {
      id: '/dedup-audit'
      path: '/dedup-audit'
      fullPath: '/dedup-audit'
      preLoaderRoute: typeof DedupAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikesearch': {
      id: '/bikesearch'
      path: '/bikesearch'
      fullPath: '/bikesearch'
      preLoaderRoute: typeof BikesearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellen': {
      id: '/bestellen'
      path: '/bestellen'
      fullPath: '/bestellen'
      preLoaderRoute: typeof BestellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/al-een-sticker': {
      id: '/al-een-sticker'
      path: '/al-een-sticker'
      fullPath: '/al-een-sticker'
      preLoaderRoute: typeof AlEenStickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-auth-check': {
      id: '/admin-auth-check'
      path: '/admin-auth-check'
      fullPath: '/admin-auth-check'
      preLoaderRoute: typeof AdminAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/m/$token': {
      id: '/m/$token'
      path: '/m/$token'
      fullPath: '/m/$token'
      preLoaderRoute: typeof MTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellen/bedankt': {
      id: '/bestellen/bedankt'
      path: '/bedankt'
      fullPath: '/bestellen/bedankt'
      preLoaderRoute: typeof BestellenBedanktRouteImport
      parentRoute: typeof BestellenRoute
    }
    '/_admin/admin-webhooks': {
      id: '/_admin/admin-webhooks'
      path: '/admin-webhooks'
      fullPath: '/admin-webhooks'
      preLoaderRoute: typeof AdminAdminWebhooksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-users': {
      id: '/_admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-shop-signups': {
      id: '/_admin/admin-shop-signups'
      path: '/admin-shop-signups'
      fullPath: '/admin-shop-signups'
      preLoaderRoute: typeof AdminAdminShopSignupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-margin-poll': {
      id: '/_admin/admin-margin-poll'
      path: '/admin-margin-poll'
      fullPath: '/admin-margin-poll'
      preLoaderRoute: typeof AdminAdminMarginPollRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-email-log': {
      id: '/_admin/admin-email-log'
      path: '/admin-email-log'
      fullPath: '/admin-email-log'
      preLoaderRoute: typeof AdminAdminEmailLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-email-events': {
      id: '/_admin/admin-email-events'
      path: '/admin-email-events'
      fullPath: '/admin-email-events'
      preLoaderRoute: typeof AdminAdminEmailEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin-audit': {
      id: '/_admin/admin-audit'
      path: '/admin-audit'
      fullPath: '/admin-audit'
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/stolen': {
      id: '/$lang/stolen'
      path: '/stolen'
      fullPath: '/$lang/stolen'
      preLoaderRoute: typeof LangStolenRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/shop': {
      id: '/$lang/shop'
      path: '/shop'
      fullPath: '/$lang/shop'
      preLoaderRoute: typeof LangShopRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/pro': {
      id: '/$lang/pro'
      path: '/pro'
      fullPath: '/$lang/pro'
      preLoaderRoute: typeof LangProRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/order': {
      id: '/$lang/order'
      path: '/order'
      fullPath: '/$lang/order'
      preLoaderRoute: typeof LangOrderRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/manufacturer': {
      id: '/$lang/manufacturer'
      path: '/manufacturer'
      fullPath: '/$lang/manufacturer'
      preLoaderRoute: typeof LangManufacturerRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/leasing': {
      id: '/$lang/leasing'
      path: '/leasing'
      fullPath: '/$lang/leasing'
      preLoaderRoute: typeof LangLeasingRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/insurance': {
      id: '/$lang/insurance'
      path: '/insurance'
      fullPath: '/$lang/insurance'
      preLoaderRoute: typeof LangInsuranceRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/bike-check': {
      id: '/$lang/bike-check'
      path: '/bike-check'
      fullPath: '/$lang/bike-check'
      preLoaderRoute: typeof LangBikeCheckRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/assistance': {
      id: '/$lang/assistance'
      path: '/assistance'
      fullPath: '/$lang/assistance'
      preLoaderRoute: typeof LangAssistanceRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/already-have-one': {
      id: '/$lang/already-have-one'
      path: '/already-have-one'
      fullPath: '/$lang/already-have-one'
      preLoaderRoute: typeof LangAlreadyHaveOneRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/api/public/vies-lookup': {
      id: '/api/public/vies-lookup'
      path: '/api/public/vies-lookup'
      fullPath: '/api/public/vies-lookup'
      preLoaderRoute: typeof ApiPublicViesLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shop-signup': {
      id: '/api/public/shop-signup'
      path: '/api/public/shop-signup'
      fullPath: '/api/public/shop-signup'
      preLoaderRoute: typeof ApiPublicShopSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/order_/thanks': {
      id: '/$lang/order_/thanks'
      path: '/order/thanks'
      fullPath: '/$lang/order/thanks'
      preLoaderRoute: typeof LangOrderThanksRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/guides/buying-second-hand': {
      id: '/$lang/guides/buying-second-hand'
      path: '/guides/buying-second-hand'
      fullPath: '/$lang/guides/buying-second-hand'
      preLoaderRoute: typeof LangGuidesBuyingSecondHandRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/api/public/payments/mollie-webhook': {
      id: '/api/public/payments/mollie-webhook'
      path: '/api/public/payments/mollie-webhook'
      fullPath: '/api/public/payments/mollie-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsMollieWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LangRouteRouteChildren {
  LangAlreadyHaveOneRoute: typeof LangAlreadyHaveOneRoute
  LangAssistanceRoute: typeof LangAssistanceRoute
  LangBikeCheckRoute: typeof LangBikeCheckRoute
  LangContactRoute: typeof LangContactRoute
  LangInsuranceRoute: typeof LangInsuranceRoute
  LangLeasingRoute: typeof LangLeasingRoute
  LangManufacturerRoute: typeof LangManufacturerRoute
  LangOrderRoute: typeof LangOrderRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangProRoute: typeof LangProRoute
  LangShopRoute: typeof LangShopRoute
  LangStolenRoute: typeof LangStolenRoute
  LangIndexRoute: typeof LangIndexRoute
  LangGuidesBuyingSecondHandRoute: typeof LangGuidesBuyingSecondHandRoute
  LangOrderThanksRoute: typeof LangOrderThanksRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAlreadyHaveOneRoute: LangAlreadyHaveOneRoute,
  LangAssistanceRoute: LangAssistanceRoute,
  LangBikeCheckRoute: LangBikeCheckRoute,
  LangContactRoute: LangContactRoute,
  LangInsuranceRoute: LangInsuranceRoute,
  LangLeasingRoute: LangLeasingRoute,
  LangManufacturerRoute: LangManufacturerRoute,
  LangOrderRoute: LangOrderRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangProRoute: LangProRoute,
  LangShopRoute: LangShopRoute,
  LangStolenRoute: LangStolenRoute,
  LangIndexRoute: LangIndexRoute,
  LangGuidesBuyingSecondHandRoute: LangGuidesBuyingSecondHandRoute,
  LangOrderThanksRoute: LangOrderThanksRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminEmailEventsRoute: typeof AdminAdminEmailEventsRoute
  AdminAdminEmailLogRoute: typeof AdminAdminEmailLogRoute
  AdminAdminMarginPollRoute: typeof AdminAdminMarginPollRoute
  AdminAdminShopSignupsRoute: typeof AdminAdminShopSignupsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminWebhooksRoute: typeof AdminAdminWebhooksRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminEmailEventsRoute: AdminAdminEmailEventsRoute,
  AdminAdminEmailLogRoute: AdminAdminEmailLogRoute,
  AdminAdminMarginPollRoute: AdminAdminMarginPollRoute,
  AdminAdminShopSignupsRoute: AdminAdminShopSignupsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminWebhooksRoute: AdminAdminWebhooksRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BestellenRouteChildren {
  BestellenBedanktRoute: typeof BestellenBedanktRoute
}

const BestellenRouteChildren: BestellenRouteChildren = {
  BestellenBedanktRoute: BestellenBedanktRoute,
}

const BestellenRouteWithChildren = BestellenRoute._addFileChildren(
  BestellenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AdminAuthCheckRoute: AdminAuthCheckRoute,
  AlEenStickerRoute: AlEenStickerRoute,
  AuthRoute: AuthRoute,
  BestellenRoute: BestellenRouteWithChildren,
  BikesearchRoute: BikesearchRoute,
  DedupAuditRoute: DedupAuditRoute,
  FietsControlerenRoute: FietsControlerenRoute,
  GestolenRoute: GestolenRoute,
  McpRoute: McpRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  MTokenRoute: MTokenRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicShopSignupRoute: ApiPublicShopSignupRoute,
  ApiPublicViesLookupRoute: ApiPublicViesLookupRoute,
  ApiPublicPaymentsMollieWebhookRoute: ApiPublicPaymentsMollieWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
